### ISSUE TITLE
CI builds may not be idempotent

### ISSUE THREAD

**Issue by poiru** [electron/libchromiumcontent#282]
@kevinsawicki CI builds currently reuse `libchromiumcontent/src` if the Chromium version was the same as the last build. This seems super dangerous to me because patches applied by one build will stay applied as long as the Chromium version doesn't change. Should we [refetch the tarball](https://github.com/electron/libchromiumcontent/pull/281/commits/429619a5c94a1dce1c472a9315e1a1fc51e9914a) each time?

**Comment by zcbenz** [comment]
Even with a very powerful machine a full rebuild of Chromium still takes too long to finish.

A probably better way is to fetch the git checkout of source code and reset the changes for each build, we tried that but reverted at b7a060b, because even checking out the git repo of Chromium can take forever on our CI machines. We might try it again after upgrading the machines.

**Comment by poiru** [comment]
@zcbenz Yeah, that seems reasonable. The CI machines only need to fetch the full Chromium repo once, right? Subsequent fetches should presumably be much faster.
