### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by 01BTC10** [electron/libchromiumcontent#302]
### Fix SSL certificate errors

If you see this error when running the python scripts:
```
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
```
Verify that the ca-certificates are installed:

    $ sudo aptitude install ca-certificates

Add this configuration to your ~/.gitconfig

```
[user]
	name = username
	email = user@email
[http]
        sslVerify = true
        sslCAinfo = /etc/ssl/certs/ca-certificates.crt

```

I had this issue while building electron and it failed only with this submodule.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
