### ISSUE TITLE
Set `is_official_build=true` for static_library builds

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#358]
@zcbenz, do we need it for "ffmpeg" config?

- [ ] Check that Electron can be built and works well with the new libcc.

**Comment by alexeykuzmin** [comment]
Reverted in #368.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
