### ISSUE TITLE
New patch: Checking pointer returned from browser plug-in. Ignoring nullptr values which would cause BAD ACCESS errors

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#399]
[047-browser_plugin_guest.patch](https://github.com/electron/libchromiumcontent/blob/master/patches/047-browser_plugin_guest.patch)

Two options:
1) If the check is really needed there, it should be upstreamed.
2) If the errors occur only because the Electron does something wrong, the Electron code should be fixed.

Anyway, the patch should be removed.

/cc @gavignus

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
