### ISSUE TITLE
a/v codecs build flag

### ISSUE THREAD

**Issue by themihai** [electron/libchromiumcontent#449]
Is it possible to enable more codecs available from ffmpeg (i.e. using a build flags) ?
 I understand the issue of licenses and patents but the laws(i.e. patent lifetime, eligibility etc) vary by jurisdiction especially in Europe so I believe the developer should have the chance to enable or disable the codecs on build time.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
