### ISSUE TITLE
disable "isTrusted" security feature

### ISSUE THREAD

**Issue by themihai** [electron/libchromiumcontent#450]
I'm trying to develop a TV application which is controlled remotely(via websockets). The issue is that I can't redirect to any new page due the "isTrusted" property that is attached to the events.
  For example if I want to simulate a keyboard event ("Enter" keydown) or a `click` event on a href  which would normally make the browser  to load the focused href, the event is ignored due this isTrusted property. Not even window.location.href/replace/attribute etc are working when they are triggered remotely (i.e. as result of a websockets command/event mechanism) .
     This `isTrusted` property makes sense on the web where clickjacking is an issue but shouldn't be an issue on desktop development.

**Comment by themihai** [comment]
Apparently there is a workaround by sending the keyboard events via the IPC process.

**Comment by wuyue92tree** [comment]
> Apparently there is a workaround by sending the keyboard events via the IPC process.

I also got this, can you show me an example? thanks

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
