### ISSUE TITLE
Header dependencies can be generated by ninja

### ISSUE THREAD

**Issue by sayrer** [electron/libchromiumcontent#467]
I saw this in:

https://github.com/electron/libchromiumcontent/blob/bf557230e6722904aa06f2730655395d835f92f2/script/create-dist#L240

ninja can describe the headers needed for any target by running:

`ninja -t deps`

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
