### ISSUE TITLE
Hide/Stop Mouse capture in electron/chromium app

### ISSUE THREAD

**Issue by richasworks** [electron/libchromiumcontent#497]
Hello, In our use case we share desktop to remote user over webrtc and need to hide local mouse in electron/chromium app, would you like to help us by giving some pointers towards writing a chromium webrtc patch to hide local mouse?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
