### ISSUE TITLE
Add a pre-commit hook to check lists of patches on disk and in .patches.yaml files

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#541]

**Comment by nornagon** [comment]
It'd be awesome if such a precommit would also check that the patches are correctly formatted, possibly by parsing them with something like the [unidiff](https://github.com/matiasb/python-unidiff/blob/master/unidiff/patch.py) python library.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
