### ISSUE TITLE
window 7 issue during build

### ISSUE THREAD

**Issue by dipt912** [electron/libchromiumcontent#549]
$ script/build -t x64
ninja: fatal: chdir to 'src\out-x64\static_library' - No such file or directory
ninja: Entering directory `src\out-x64\static_library'
Traceback (most recent call last):
  File "script/build", line 79, in <module>
    sys.exit(main())
  File "script/build", line 52, in main
    run_ninja(os.path.relpath(out_dir), target=target, env=env)
  File "C:\Users\Diptesh\workspace\libchromiumcontent\script\lib\ninja.py", line 26, in run
    subprocess.check_call(args, env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Diptesh\\workspace\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-x64\\static_library', 'libchromiumcontent/chromiumcontent:chromiumcontent']' returned non-zero exit status 1

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
