### ISSUE TITLE
How to use in electron?

### ISSUE THREAD

**Issue by manang** [electron/libchromiumcontent#631]
Hi,
I need to modify the webrtc source.
Which files I have to use inside electron to use a modified libchromium lib?
Thanks

**Comment by alexeykuzmin** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.  Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

You may want to check the [Chromium development with Electron](https://github.com/electron/electron/blob/master/docs/development/chromium-development.md#chromium-development-with-electron) docs first.
