### ISSUE TITLE
error in script/create-dist

### ISSUE THREAD

**Issue by manang** [electron/libchromiumcontent#632]
Hi,
there is a typo in create-dist script.
when I try to create the dist output file, the script search ffmpeg.dylib file in a folder called native_mksnapshot, but it is not available in dist/main/
I guess that the folder is dist/main/ffmpeg.
could you confirm it?
Thanks

**Comment by alexeykuzmin** [comment]
@manang How exactly you run the `create-dist` script? Any arguments?
What type of build you have run before that? Just `script/build` without any arguments?

**Comment by manang** [comment]
Hi,
I launched
$ script/update -t x64
$ script/build -t x64
and after
$ script/create-dist

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
