### ISSUE TITLE
When will we hit at least Chrome 67 for BigInt()  ?

### ISSUE THREAD

**Issue by kosso** [electron/libchromiumcontent#646]
Since Chrome 67 introduced BigInt() https://developers.google.com/web/updates/2018/05/bigint

.. any idea when electron might be able to use it? 

I see it recently hit Chrome 66.
I have a pressing need within an app to use Big Integers in the JS. 

Thanks.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
