### ISSUE TITLE
Clang libc6 version dependency

### ISSUE THREAD

**Issue by nikmartin** [electron/libchromiumcontent#83]
compiling libchromiumcontent from source is listed as a way to compile other projects on Debian Wheezy that use it. The issue is Debian 7 stable uses libc6 2.13, when projects like Atom.io package libchromiumcontent .so as a build dependency (:confounded:) which is compiled against libc6 2.14. So I clone this repo, and it now ALSO requires libc6 2.14:

```
../../third_party/llvm-build/Release+Asserts/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ../../third_party/llvm-build/Release+Asserts/bin/clang)
../../third_party/llvm-build/Release+Asserts/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ../../third_party/llvm-build/Release+Asserts/bin/clang)
../../third_party/llvm-build/Release+Asserts/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/nmartinssd/Projects/libchromiumcontent/vendor/chromium/src/third_party/llvm-build/Release+Asserts/bin/../lib/libstdc++.so.6)
ninja: build stopped: subcommand failed.
```

Is this intentional? it seems clang which is packaged with libchromiumcontent now also requires libc6 2.14 or  higher

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
